<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" />
    <PackageReference Include="TimeZoneConverter" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\DirectoryService.Shared\DirectoryService.Shared.csproj" />
  </ItemGroup>
</Project>
